fix: make it of "module" type
When running tests, node 20 complains:
"
SyntaxError: Cannot use import statement outside a module
"
(interestingly enough, previous versions of node do not complain)

Even prior to using node v20, there has been confusion, as seen from e.g.
https://github.com/swiing/BitArray/commit/b380b8892df0ef1d951e5401d7c2e64d1366eead
(Note on why this is related: modules _do_ require use of file extensions
in import statements)

Hopefully this change makes it clean for all (node, ts-node
and dependents importing this package)